/**
 * Phase 39 — Deployment Agents
 * Detect runtime tools; generate configs; run safe deploy actions locally or on VPS.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join } from "path";
import { spawn } from "child_process";
import { randomUUID } from "crypto";
import { WORKSPACE } from "./codeRunner.js";
import { log } from "./logger.js";
import { execOnVps } from "./vpsBroker.js";
import { writeWorkspaceFile } from "./fileManager.js";
import { createCheckpoint } from "./patchEngine.js";

const DATA = join(process.cwd(), ".data");
const DEPLOY_LOG = join(DATA, "deploy-log.json");
mkdirSync(DATA, { recursive: true });

export type DeployTool =
  | "docker"
  | "compose"
  | "pm2"
  | "nginx"
  | "caddy"
  | "apache2"
  | "systemctl"
  | "certbot";

export type DeployAction =
  | "detect"
  | "dockerfile"
  | "compose"
  | "pm2_ecosystem"
  | "nginx_site"
  | "caddyfile"
  | "build"
  | "up"
  | "down"
  | "pm2_start"
  | "status";

type DeployEvent = {
  id: string;
  action: string;
  target: string;
  ok: boolean;
  detail: string;
  at: string;
};

function loadLog(): DeployEvent[] {
  try {
    if (!existsSync(DEPLOY_LOG)) return [];
    return JSON.parse(readFileSync(DEPLOY_LOG, "utf8"));
  } catch {
    return [];
  }
}

function pushLog(ev: Omit<DeployEvent, "id" | "at">) {
  const rows = loadLog();
  rows.unshift({
    id: randomUUID().slice(0, 8),
    at: new Date().toISOString(),
    ...ev,
  });
  try {
    writeFileSync(DEPLOY_LOG, JSON.stringify(rows.slice(0, 100), null, 2));
  } catch {
    /* */
  }
}

function runLocal(cmd: string, args: string[], cwd?: string): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, {
      cwd: cwd || WORKSPACE,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      resolve({ code: 124, stdout, stderr: stderr + "\n[timeout]" });
    }, 60000);
    child.stdout?.on("data", (d) => {
      stdout += d.toString();
      if (stdout.length > 80_000) stdout = stdout.slice(-80_000);
    });
    child.stderr?.on("data", (d) => {
      stderr += d.toString();
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? 1, stdout, stderr });
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ code: 1, stdout: "", stderr: err.message });
    });
  });
}

async function which(tool: string): Promise<boolean> {
  const r = await runLocal("bash", ["-lc", `command -v ${tool} >/dev/null 2>&1 && echo YES || echo NO`]);
  return r.stdout.includes("YES");
}

export async function detectTools(): Promise<Record<DeployTool, boolean>> {
  const tools: DeployTool[] = [
    "docker",
    "compose",
    "pm2",
    "nginx",
    "caddy",
    "apache2",
    "systemctl",
    "certbot",
  ];
  const out = {} as Record<DeployTool, boolean>;
  for (const t of tools) {
    if (t === "compose") {
      out.compose = (await which("docker-compose")) || (await which("docker"));
    } else {
      out[t] = await which(t);
    }
  }
  // docker compose plugin
  if (out.docker) {
    const r = await runLocal("docker", ["compose", "version"]);
    if (r.code === 0) out.compose = true;
  }
  return out;
}

export async function generateDockerfile(opts?: {
  nodeVersion?: string;
  startCmd?: string;
}): Promise<{ path: string; content: string }> {
  const content = `# Generated by AI Agent Pro — Phase 39
FROM node:${opts?.nodeVersion || "22"}-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev || npm install --omit=dev
COPY . .
ENV NODE_ENV=production
EXPOSE 3000
CMD ${JSON.stringify(opts?.startCmd || ["npm", "start"])}
`;
  try {
    await createCheckpoint("deploy-dockerfile");
  } catch {
    /* */
  }
  await writeWorkspaceFile("Dockerfile", content);
  pushLog({ action: "dockerfile", target: "local", ok: true, detail: "Dockerfile written" });
  return { path: "Dockerfile", content };
}

export async function generateCompose(opts?: {
  serviceName?: string;
  port?: number;
}): Promise<{ path: string; content: string }> {
  const name = opts?.serviceName || "app";
  const port = opts?.port || 3000;
  const content = `# Generated by AI Agent Pro — Phase 39
services:
  ${name}:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - PORT=${port}
      - NODE_ENV=production
    restart: unless-stopped
`;
  try {
    await createCheckpoint("deploy-compose");
  } catch {
    /* */
  }
  await writeWorkspaceFile("docker-compose.yml", content);
  pushLog({ action: "compose", target: "local", ok: true, detail: "docker-compose.yml written" });
  return { path: "docker-compose.yml", content };
}

export async function generatePm2Ecosystem(opts?: {
  name?: string;
  script?: string;
}): Promise<{ path: string; content: string }> {
  const content = `module.exports = {
  apps: [
    {
      name: ${JSON.stringify(opts?.name || "ai-agent-pro")},
      script: ${JSON.stringify(opts?.script || "npm")},
      args: "start",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production", PORT: 3000 },
    },
  ],
};
`;
  await writeWorkspaceFile("ecosystem.config.cjs", content);
  pushLog({ action: "pm2_ecosystem", target: "local", ok: true, detail: "ecosystem.config.cjs written" });
  return { path: "ecosystem.config.cjs", content };
}

export async function generateNginxSite(opts?: {
  serverName?: string;
  port?: number;
}): Promise<{ path: string; content: string }> {
  const serverName = opts?.serverName || "_";
  const port = opts?.port || 3000;
  const content = `# Generated by AI Agent Pro — Phase 39
server {
    listen 80;
    server_name ${serverName};

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \\$host;
        proxy_set_header X-Real-IP \\$remote_addr;
        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \\$scheme;
    }
}
`;
  await writeWorkspaceFile("deploy/nginx.conf", content);
  pushLog({ action: "nginx_site", target: "local", ok: true, detail: "deploy/nginx.conf written" });
  return { path: "deploy/nginx.conf", content };
}

export async function generateCaddyfile(opts?: {
  domain?: string;
  port?: number;
}): Promise<{ path: string; content: string }> {
  const domain = opts?.domain || "localhost";
  const port = opts?.port || 3000;
  const content = `# Generated by AI Agent Pro — Phase 39
${domain} {
    reverse_proxy 127.0.0.1:${port}
}
`;
  await writeWorkspaceFile("deploy/Caddyfile", content);
  pushLog({ action: "caddyfile", target: "local", ok: true, detail: "deploy/Caddyfile written" });
  return { path: "deploy/Caddyfile", content };
}

export async function dockerBuild(tag = "ai-agent-pro:latest"): Promise<{ ok: boolean; output: string }> {
  const r = await runLocal("docker", ["build", "-t", tag, "."]);
  const ok = r.code === 0;
  pushLog({ action: "build", target: "local", ok, detail: (r.stderr || r.stdout).slice(0, 400) });
  return { ok, output: (r.stdout + "\n" + r.stderr).slice(0, 4000) };
}

export async function composeUp(): Promise<{ ok: boolean; output: string }> {
  let r = await runLocal("docker", ["compose", "up", "-d", "--build"]);
  if (r.code !== 0) {
    r = await runLocal("docker-compose", ["up", "-d", "--build"]);
  }
  const ok = r.code === 0;
  pushLog({ action: "up", target: "local", ok, detail: (r.stderr || r.stdout).slice(0, 400) });
  return { ok, output: (r.stdout + "\n" + r.stderr).slice(0, 4000) };
}

export async function composeDown(): Promise<{ ok: boolean; output: string }> {
  let r = await runLocal("docker", ["compose", "down"]);
  if (r.code !== 0) r = await runLocal("docker-compose", ["down"]);
  const ok = r.code === 0;
  pushLog({ action: "down", target: "local", ok, detail: (r.stderr || r.stdout).slice(0, 400) });
  return { ok, output: (r.stdout + "\n" + r.stderr).slice(0, 2000) };
}

export async function pm2Start(): Promise<{ ok: boolean; output: string }> {
  const r = await runLocal("pm2", ["start", "ecosystem.config.cjs"]);
  const ok = r.code === 0;
  pushLog({ action: "pm2_start", target: "local", ok, detail: (r.stderr || r.stdout).slice(0, 400) });
  return { ok, output: (r.stdout + "\n" + r.stderr).slice(0, 2000) };
}

export async function deployStatus(): Promise<{
  tools: Record<DeployTool, boolean>;
  recent: DeployEvent[];
}> {
  return { tools: await detectTools(), recent: loadLog().slice(0, 15) };
}

/** Run a high-level deploy recipe */
export async function runDeployRecipe(
  recipe: "node-docker" | "node-pm2" | "static-nginx",
  opts?: { domain?: string; port?: number; vpsId?: string }
): Promise<{ steps: { step: string; ok: boolean; detail: string }[] }> {
  const steps: { step: string; ok: boolean; detail: string }[] = [];
  const port = opts?.port || 3000;

  if (recipe === "node-docker") {
    const df = await generateDockerfile({});
    steps.push({ step: "dockerfile", ok: true, detail: df.path });
    const cmp = await generateCompose({ port });
    steps.push({ step: "compose", ok: true, detail: cmp.path });
    if (!opts?.vpsId) {
      const tools = await detectTools();
      if (tools.docker) {
        const b = await dockerBuild();
        steps.push({ step: "build", ok: b.ok, detail: b.output.slice(0, 200) });
      } else {
        steps.push({ step: "build", ok: false, detail: "docker not installed" });
      }
    }
  } else if (recipe === "node-pm2") {
    const eco = await generatePm2Ecosystem({});
    steps.push({ step: "ecosystem", ok: true, detail: eco.path });
    const tools = await detectTools();
    if (tools.pm2 && !opts?.vpsId) {
      const p = await pm2Start();
      steps.push({ step: "pm2_start", ok: p.ok, detail: p.output.slice(0, 200) });
    } else {
      steps.push({ step: "pm2_start", ok: false, detail: tools.pm2 ? "skipped remote" : "pm2 not installed" });
    }
  } else if (recipe === "static-nginx") {
    const n = await generateNginxSite({ serverName: opts?.domain || "_", port });
    steps.push({ step: "nginx", ok: true, detail: n.path });
    const c = await generateCaddyfile({ domain: opts?.domain || "localhost", port });
    steps.push({ step: "caddy", ok: true, detail: c.path });
  }

  // optional remote copy hint via VPS
  if (opts?.vpsId) {
    try {
      const r = await execOnVps(opts.vpsId, "mkdir -p ~/app && echo READY");
      steps.push({
        step: "vps_prep",
        ok: r.code === 0,
        detail: (r.stdout || r.stderr).slice(0, 200),
      });
    } catch (e: any) {
      steps.push({ step: "vps_prep", ok: false, detail: e.message });
    }
  }

  log("info", `Deploy recipe ${recipe} steps=${steps.length}`, "deploy");
  return { steps };
}


/** Aliases + helpers for API compatibility */
export const detectDeployTools = detectTools;
export const generateNginxConfig = generateNginxSite;

export async function generateDeployPack(opts?: {
  serviceName?: string;
  port?: number;
  domain?: string;
  nodeVersion?: string;
}) {
  const port = opts?.port || 3000;
  const df = await generateDockerfile({ nodeVersion: opts?.nodeVersion });
  const cmp = await generateCompose({ serviceName: opts?.serviceName, port });
  const pm2 = await generatePm2Ecosystem({ name: opts?.serviceName });
  const nginx = await generateNginxSite({ serverName: opts?.domain || "_", port });
  const caddy = await generateCaddyfile({ domain: opts?.domain || "localhost", port });
  return {
    files: [df.path, cmp.path, pm2.path, nginx.path, caddy.path],
    port,
    domain: opts?.domain,
  };
}

export function sslRenewHint(domain?: string) {
  const d = domain || "example.com";
  return {
    certbot: `sudo certbot --nginx -d ${d}`,
    caddy: "Caddy obtains/renews certs automatically",
    manual: "Place fullchain.pem and privkey.pem; reload nginx/caddy",
  };
}

export async function pm2Status(): Promise<{ ok: boolean; output: string }> {
  const r = await runLocal("pm2", ["status"]);
  return { ok: r.code === 0, output: (r.stdout + "\n" + r.stderr).slice(0, 4000) };
}

export async function deployToVpsHint(vpsId: string) {
  return {
    vpsId,
    steps: [
      "Register SSH key in Accounts/VPS",
      "scp -r . user@host:~/app",
      "ssh user@host 'cd app && npm i && npm start'",
      "Or: docker compose up -d on remote",
    ],
  };
}

export function listDeployLogs(limit = 30) {
  return loadLog().slice(0, limit);
}
