/**
 * Phase 31 — Background AI Workers
 * Parallel workers per workspace: code / test / docs / logs
 */

import { randomUUID } from "crypto";
import { log } from "./logger.js";
import { createTask, listTasks, type Task } from "./taskQueue.js";
import { runCode } from "./codeRunner.js";
import { writeWorkspaceFile, readWorkspaceFile, listAllFiles } from "./fileManager.js";
import { addEntry } from "./workspaceMemory.js";
import { getLogs } from "./logger.js";

export type WorkerKind = "code" | "test" | "docs" | "logs";
export type WorkerStatus = "idle" | "running" | "stopped" | "error";

export type Worker = {
  id: string;
  kind: WorkerKind;
  name: string;
  status: WorkerStatus;
  workspaceId: string;
  createdAt: string;
  lastRunAt?: string;
  lastResult?: any;
  lastError?: string;
  autoLoop: boolean;
  intervalMs: number;
};

const workers = new Map<string, Worker>();
const timers = new Map<string, ReturnType<typeof setInterval>>();

const KIND_META: Record<WorkerKind, { name: string; defaultInterval: number }> = {
  code: { name: "Coder", defaultInterval: 0 },
  test: { name: "Tester", defaultInterval: 0 },
  docs: { name: "Docs", defaultInterval: 0 },
  logs: { name: "Log Monitor", defaultInterval: 15000 },
};

export function listWorkers(workspaceId = "default"): Worker[] {
  return [...workers.values()]
    .filter((w) => w.workspaceId === workspaceId)
    .sort((a, b) => a.kind.localeCompare(b.kind));
}

export function getWorker(id: string): Worker | null {
  return workers.get(id) || null;
}

export function spawnWorker(opts: {
  kind: WorkerKind;
  workspaceId?: string;
  autoLoop?: boolean;
  intervalMs?: number;
  name?: string;
}): Worker {
  const kind = opts.kind;
  const meta = KIND_META[kind];
  if (!meta) throw new Error("Invalid worker kind");

  // one of each kind per workspace
  const existing = listWorkers(opts.workspaceId || "default").find((w) => w.kind === kind);
  if (existing && existing.status !== "stopped") {
    return existing;
  }

  const w: Worker = {
    id: randomUUID().slice(0, 10),
    kind,
    name: opts.name || meta.name,
    status: "idle",
    workspaceId: opts.workspaceId || "default",
    createdAt: new Date().toISOString(),
    autoLoop: !!opts.autoLoop,
    intervalMs: opts.intervalMs ?? meta.defaultInterval,
  };
  workers.set(w.id, w);
  log("info", `Worker spawned: ${w.kind} ${w.id}`, "workers");

  if (w.autoLoop && w.intervalMs > 0) {
    startLoop(w.id);
  }
  return w;
}

export function stopWorker(id: string): Worker | null {
  const w = workers.get(id);
  if (!w) return null;
  const t = timers.get(id);
  if (t) {
    clearInterval(t);
    timers.delete(id);
  }
  w.status = "stopped";
  w.autoLoop = false;
  workers.set(id, w);
  return w;
}

export function stopAllWorkers(workspaceId = "default") {
  for (const w of listWorkers(workspaceId)) stopWorker(w.id);
}

function startLoop(id: string) {
  const w = workers.get(id);
  if (!w || w.intervalMs <= 0) return;
  if (timers.has(id)) return;
  const timer = setInterval(() => {
    runWorker(id).catch(() => {});
  }, w.intervalMs);
  timers.set(id, timer);
}

/** Run one unit of work for a worker */
export async function runWorker(
  id: string,
  payload?: Record<string, any>
): Promise<Worker> {
  const w = workers.get(id);
  if (!w) throw new Error("Worker not found");
  if (w.status === "running") return w;

  w.status = "running";
  w.lastRunAt = new Date().toISOString();
  workers.set(id, w);

  try {
    let result: any;
    switch (w.kind) {
      case "code":
        result = await runCodeWorker(payload);
        break;
      case "test":
        result = await runTestWorker(payload);
        break;
      case "docs":
        result = await runDocsWorker(payload);
        break;
      case "logs":
        result = await runLogsWorker(payload);
        break;
      default:
        result = { skipped: true };
    }
    w.lastResult = result;
    w.lastError = undefined;
    w.status = "idle";
    workers.set(id, w);
    log("info", `Worker done: ${w.kind}`, "workers");
  } catch (e: any) {
    w.lastError = e.message || String(e);
    w.status = "error";
    workers.set(id, w);
    log("error", `Worker error ${w.kind}: ${w.lastError}`, "workers");
  }
  return w;
}

async function runCodeWorker(payload?: Record<string, any>) {
  const path = payload?.path || "worker_hello.py";
  const content =
    payload?.content ||
    `# generated by code worker\nprint("code worker ok")\n`;
  await writeWorkspaceFile(path, content);
  const run = await runCode("python", content);
  createTask({
    title: `code-worker wrote ${path}`,
    type: "agent_note",
    payload: { path, exit: run.exitCode },
  });
  return { path, exitCode: run.exitCode, stdout: run.stdout?.slice(0, 500) };
}

async function runTestWorker(payload?: Record<string, any>) {
  // Prefer pytest/unittest file if present; else smoke python assert
  const files = await listAllFiles(".");
  const testFile = files.find((f) => /test_.*\.py$/.test(f) || f.endsWith(".test.js"));
  if (testFile?.endsWith(".py")) {
    const r = await runCode("bash", `cd "$PWD" && python3 -m pytest ${testFile} -q 2>&1 | tail -20`);
    return { runner: "pytest", file: testFile, exitCode: r.exitCode, output: (r.stdout || r.stderr).slice(0, 1000) };
  }
  const code = payload?.code || "assert 1 + 1 == 2\nprint('tests ok')\n";
  const r = await runCode("python", code);
  return { runner: "inline", exitCode: r.exitCode, output: (r.stdout || r.stderr).slice(0, 500) };
}

async function runDocsWorker(payload?: Record<string, any>) {
  const files = await listAllFiles(".");
  const sample = files.slice(0, 30);
  const md =
    payload?.content ||
    `# Workspace docs (auto)\n\nGenerated by docs worker.\n\n## Files\n\n${sample.map((f) => `- \`${f}\``).join("\n")}\n`;
  await writeWorkspaceFile(payload?.path || "WORKER_DOCS.md", md);
  addEntry("default", {
    section: "team_notes",
    title: "docs-worker",
    content: `Updated docs with ${sample.length} files listed`,
  });
  return { path: payload?.path || "WORKER_DOCS.md", filesListed: sample.length };
}

async function runLogsWorker(_payload?: Record<string, any>) {
  const logs = getLogs({ limit: 20 });
  const errors = logs.filter((l) => l.level === "error" || l.level === "warn");
  if (errors.length) {
    addEntry("default", {
      section: "bugs",
      title: `log-alerts-${new Date().toISOString().slice(11, 19)}`,
      content: errors
        .slice(0, 5)
        .map((e) => `[${e.level}] ${e.source}: ${e.message}`)
        .join("\n"),
      tags: ["logs", "auto"],
    });
  }
  return {
    scanned: logs.length,
    errors: errors.length,
    latest: logs.slice(0, 5).map((l) => ({ level: l.level, message: l.message.slice(0, 80) })),
  };
}

/** Spawn the standard four-worker squad */
export function spawnSquad(workspaceId = "default"): Worker[] {
  const kinds: WorkerKind[] = ["code", "test", "docs", "logs"];
  return kinds.map((kind) =>
    spawnWorker({
      kind,
      workspaceId,
      autoLoop: kind === "logs",
      intervalMs: kind === "logs" ? 15000 : 0,
    })
  );
}

/** Run code+test+docs once in parallel */
export async function runSquadOnce(workspaceId = "default") {
  let squad = listWorkers(workspaceId);
  if (squad.length < 3) squad = spawnSquad(workspaceId);
  const targets = squad.filter((w) => w.kind !== "logs" || true);
  const results = await Promise.all(targets.map((w) => runWorker(w.id)));
  return results;
}

export function workerStats() {
  const all = [...workers.values()];
  return {
    total: all.length,
    idle: all.filter((w) => w.status === "idle").length,
    running: all.filter((w) => w.status === "running").length,
    error: all.filter((w) => w.status === "error").length,
    stopped: all.filter((w) => w.status === "stopped").length,
    byKind: {
      code: all.filter((w) => w.kind === "code").length,
      test: all.filter((w) => w.kind === "test").length,
      docs: all.filter((w) => w.kind === "docs").length,
      logs: all.filter((w) => w.kind === "logs").length,
    },
  };
}
